ALTER TABLE llm_turns ADD COLUMN IF NOT EXISTS policy_action VARCHAR(32) NOT NULL DEFAULT 'discard';
ALTER TABLE llm_turns ADD COLUMN IF NOT EXISTS auto_reply_eligible BOOLEAN NOT NULL DEFAULT FALSE;
